name: 'Deploy Ghost Theme'
description: 'Build & deploy a theme to your Ghost site'
branding:
  icon: 'cloud-lightning'
  color: 'gray-dark'
inputs:
  api-url:
    description: 'https://2ndchance.ghost.io'
    required: true
  api-key:
    description: 'eabac8968e5a00a7592fb4be5b'
    required: true
  exclude:
    description: 'Files or folders to exclude (space-separated list)'
    required: false
  theme-name:
    description: 'A custom theme name that overrides the default name in package.json'
    required: false
  file:
    description: 'Path to a built zip file. If this is included, the `exclude` and `theme-name` options are ignored'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
